language: haskell
ghc: 
  - 7.4
  - 7.6
  - 7.8

sudo: true

install:
  - sudo apt-get install libgtk-3-dev
  - cabal install --only-dependencies --enable-tests

notifications:
  email:
    on_success: change
    on_failure: change
