language: haskell
ghc: 
  - 7.4
  - 7.6
  - 7.8

install:
  - sudo apt-get install libgtk-3-dev
  - cabal install Cabal
  - cabal install alex happy 
  - cabal install gtk2hs-buildtools
  - cabal install --only-dependencies --enable-tests

notifications:
  email:
    on_success: change
    on_failure: change
